Backend/config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  get '/entries' => 'entries#show_entries_by_user'
  get '/entries/new' => 'entries#new'
  post '/entries/create' => 'entries#create'
  get '/entries/show/(:id)' => 'entries#show'
  patch '/entries/:id' => 'entries#update'
  put '/entries/:id' => 'entries#update'
  get '/entries/edit/:id' => 'entries#edit'
end

Backend/app/models/entry.rb
class Entry < ActiveRecord::Base

	scope :get_entries_by_user, lambda {|query|
	  where(["user_id LIKE ?", "#{query}"])
	}

end

Backend/app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

end

Backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        flash[:alert] = "Access denied."
        redirect_to root_url
      end
    end

    def authenticate_user!
      if !current_user
        flash[:alert] = 'You need to sign in for access to this page.'
        redirect_to root_url
      end
    end

end

Backend/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	before_filter :authenticate_user!
	# TODO: only the authorized user can create/view entries

	def new
		@entry = Entry.new
	end
	
	def show
		@entry = Entry.find(params[:id])
		if @entry.user_id != current_user.id
			flash[:notice] = "The entry does not belong to you!"
			redirect_to(:action => 'show_entries_by_user')
		end
	end

	def create
		@entry = Entry.new(entry_params)

		if @entry.save
			redirect_to(:action => 'show_entries_by_user')
		else
			flash[:notice] = "The entry could not be saved!"
		    render 'new'
		end
	end

	def edit
		@entry = Entry.find(params[:id])
	end

	def update
		@entry = Entry.find(params[:id])
		
		if @entry.update(entry_params)
			redirect_to(:action => 'show_entries_by_user')
		else
			flash[:notice] = "The entry could not be saved!"
		    render 'edit'
		end
	end

	def show_entries_by_user
		if user_signed_in?
			@entries = Entry.get_entries_by_user(current_user.id)
		else
			flash[:notice] = "You are not logged in!"
			redirect_to(:controller => 'visitors', :action => 'index')
		end
	end

	private
		def entry_params
			params.require(:entry).permit(:user_id, :device, :content, :message)
		end

end

Backend/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    session[:user_name] = user.name
    flash[:notice] = 'Signed in!'
    redirect_to root_url
  end

  def destroy
    reset_session
    flash[:notice] = 'Signed out!'
    redirect_to root_url
  end

  def failure
    flash[:alert] = "Authentication error: #{params[:message].humanize}"
    redirect_to root_url
  end

end

Backend/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

Backend/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def index
	end
end

Backend/app/helpers/application_helper.rb
module ApplicationHelper
end

Backend/app/helpers/entries_helper.rb
module EntriesHelper
end

Backend/app/views/entries/_form.html.erb
<!-- This will display the errors in case the form does not submit. -->
<% if @entry.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@entry.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- These are the form fields. -->
<%= f.hidden_field :user_id, :value => current_user.id %>
<%= f.hidden_field :device, :value => 'web' %>

<p>
  <%= f.label :content %><br>
  <%= f.text_field :content %>
</p>

<p>
  <%= f.label :message %><br>
  <%= f.text_area :message %>
</p>

<p>
  <%= f.submit %>
</p>

Backend/app/views/entries/edit.html.erb
<h1>Edit Entry</h1>

<!-- Form for creating new entries. -->
<%= form_for(:entry, :url => {:action => 'update', :id => @entry.id}, :method => :put) do |f| %>

    <%= render(:partial => "form", :locals => {:f => f}) %>

<% end %>

<!-- Go back to the entries page. -->
<%= link_to 'Back', action: 'show_entries_by_user' %>

Backend/app/views/entries/new.html.erb
<!-- Form for creating new entries. -->
<%= form_for :entry, :url => {:action => 'create'} do |f| %> 

  <!-- This will display the errors in case the form does not submit. -->
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@entry.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <!-- These are the form fields. -->
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :device, :value => 'web' %>

  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>

  <p>
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </p>

  <p>
    <%= f.submit %>
  </p>

  <% end %>

  <!-- Go back to the entries page. -->

Backend/app/views/entries/show.html.erb
<h3>Entry</h3>
<p>
	<b>User:</b> <%= @entry.user_id if @entry.user_id %>
	<b>Content:</b> <%= @entry.content if @entry.content %>
	<b>Message:</b> <%= @entry.message if @entry.message %>
	<b>Created At:</b> <%= @entry.created_at if @entry.created_at %>
</p>

Backend/app/views/entries/show_entries_by_user.html.erb
<h2>Entries by: <%= current_user.name %></h2>
<% @entries.each do |entry| %>
	<h3>Entry</h3>
	<p>
		<b>Content:</b> <%= entry.content if entry.content %>
		<%= link_to 'Show', :action => 'show', :id => entry.id %>
		<%= link_to 'Edit', {:action => 'edit', :id => entry.id} %>
	</p>
<% end %>

Backend/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in with Facebook', signin_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'View Entries', entries_path %></li>
  <li><%= link_to 'Create Entry', entries_new_path %></li>
<% end %>

Backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Slynkee</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	
	<body>
		<%= render(:partial => "layouts/navigation_links") %>
		
		<% flash.each do |name, msg| %>
			<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
			  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			</div>
		<% end %>
		
		<%= yield %>
	</body>

</html>

Backend/app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>Slynkee</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

Backend/app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>

Backend/app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

Backend/app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>

Backend/app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>